include:
  - project: 'platform/pipelines-templates'
    file: '/build/node/template-node-npm.yml'
    ref: master
  - project: 'platform/pipelines-templates'
    file: '/build/node/template-node-npm-test-latest.yml'
    ref: master

default:
  image: node:12.19.0-alpine

variables:
  IMAGE_NAME: platform-development/get-shipping-cost
